### ISSUE TITLE
Sdr

### ISSUE THREAD

**Issue by Hunterleeb** [CyZooNiC/cyberdeck#2]
Was wondering if you could link what sdr you used?

**Comment by sschueller** [comment]
I am currently using this one: https://www.aliexpress.com/item/1005001271827620.html and I have used this one as well: https://www.aliexpress.com/item/32936334224.html

I am considering getting a HackRF One eventually.

**Comment by Hunterleeb** [comment]
Awsome man thank you so much! I really appreciate it. Are all of those 3d
models on your github everything I’ll need as far as the aluminum plates,
storage bin and the 3d printed brackets?

**Comment by sschueller** [comment]
Currently missing from the github is the 3d printed keyboard mounting brackets which are a bit of a mess.I will try to sort those out and get them online as well. I have also not finished the software for the esp32 so that is currently not online either.

Also checkout the cyberdeck cafe on discord: https://discord.gg/HVDMKGrR

**Comment by Hunterleeb** [comment]
Perfect thank you I was gonna say I couldn’t find anything on those parts
on there! Is there any way I could pay you to print me the 3d parts you
used assuming you own a 3d printer? It would just be easier on my end to
not have to deal with sending the files to someone to have it done but
completely get it if your too busy or unable to do that. Again really
appreciate the response and I just joined the discord!

**Comment by sschueller** [comment]
Sadly at the moment none of my 3d printers are operational and I currently don't know when I have to time to get them running again (highly depends on what project I work on next which I don't know right now). 

I would recommend just getting one like a Creality Ender 3 (under USD 200) or if you have the money a Prusia 3d printer. I would not recommend getting a SLA printer for this as the parts needs to be somewhat strong and if you don't plan on printing small models SLA printers are just messy. Alternatively you can go to a local maker space where you can rent them. The parts are all printed in PETG which is more resilient than PLA but almost as easy to print.

**Comment by Hunterleeb** [comment]
Hey man was curious if you’d be interested in selling you cyber deck?

**Comment by sschueller** [comment]
Sorry, not at this time.
